### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by julionce** [microROS/apps#20]
Could we rename this repo as **nuttx_apps** in order to follow the same philosophy as in FreeRTOS and Zephyr?

**Comment by iluetkeb** [comment]
Sounds good to me, but let's ask generally on the ofera channel in Slack, please.

**Comment by iluetkeb** [comment]
Do we have consensus here? If yes, can we get a list of tasks to perform once this is done (I believe that moving a repo will cause github to redirect for a while, but we should still adjust the repo lists and stuff).

* [ ] update micro-ros-build repo-lists for dashing
* [ ] update micro-ros-build repo-lists for crystal

anything else?

**Comment by pablogs9** [comment]
Hi @FranFin could we retake this, as we have talked?

**Comment by ralph-lange** [comment]
+1 for renaming it.

**Comment by pablogs9** [comment]
Closing since renamed
