### ISSUE TITLE
micro_ROS/apps/ directory does not include uros_pingpong folder.

### ISSUE THREAD

**Issue by MARLARCHAN** [microROS/apps#26]
micro_ROS/apps/examples directory does not include uros_pingpong folder.
So, cannot copy Kconfig, Make.defs, Makefile, app.c files.

![Screenshot from 2020-07-22 15-40-42](https://user-images.githubusercontent.com/46348612/88148940-f2f7a080-cc31-11ea-9af0-5cf4cb2e44d1.png)

**Comment by pablogs9** [comment]
https://github.com/micro-ROS/apps/tree/foxy/examples/uros_pingpong

**Comment by MARLARCHAN** [comment]
Dear pablogs9,
    Thank you for your information.

**Comment by pablogs9** [comment]
Close if resolved please
