### ISSUE TITLE
Status of NuttX

### ISSUE THREAD

**Issue by eden-desta** [microROS/apps#34]
Hi folks,
hope all is well! Wanted to check in on the status of NuttX and integration with uROS. I have worked with both Zephyr and FreeRTOS. And I was really interested in the potential of porting over some of the boards I use to NuttX. 

Looks like NuttX just release a v10.1 which looks elite: https://bitbucket.org/patacongo/nuttx/src/master/

Let me know definitely defintely would be super cool to have this side fully supported as well!!

Thank you!

**Comment by ralph-lange** [comment]
Hi @eden-desta, the micro-ROS component for NuttX, cf. https://github.com/micro-ROS/micro_ros_nuttx_app, has recently been updated and tested for NuttX v10 and v10.1.

**Comment by pablogs9** [comment]
@eden-desta it would be super nice if you provide feedback to this NuttX 10.x example app for micro-ROS. Please open issues there for any problem you have.

**Comment by eden-desta** [comment]
Guys this is brilliant! Im looking forward to testing this out! I will close this then and let you all know if there is anything I notice! :D
